#**Assignment - Numpy**

**Therotical Problem**


**Q.1**- Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

**Ans:**- NumPy (Numerical Python) is a library that adds support for large, multi-dimensional arrays and matrices, along with a wide range of high-performance mathematical functions to operate on them.

**Purpose:**-The purpose of NumPy is to provide a robust and efficient way to perform numerical computations in Python, making it an essential tool for scientific computing and data analysis.

**Advantages:**- Speed: NumPy operations are implemented in C, allowing them to run faster than pure Python loops. This is especially important for large datasets where performance is crucial.

Memory Efficiency: NumPy arrays require less memory than Python lists due to their fixed data type and contiguous memory allocation, making them more efficient for large-scale data storage.

Broadcasting: NumPy supports broadcasting, which allows operations to be performed on arrays of different shapes without explicit looping. This feature simplifies coding and enhances performance.

**NumPy enhances Python's capabilities for numerical operations in several ways:**

1. Multi-dimensional arrays: NumPy introduces support for multi-dimensional arrays, enabling efficient storage and manipulation of large datasets.
2. Vectorized operations: NumPy's vectorized operations allow for fast and concise computations on entire arrays, reducing the need for loops.
3. High-performance functions: NumPy provides an extensive range of optimized mathematical functions, including linear algebra, Fourier transform, and random number generation.


**Q.2** Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?



**Ans:**-NumPy's np.mean() and np.average() functions both calculate the average of an array, but they have some subtle differences:

**np.mean():**

- Calculates the arithmetic mean of the array elements.
- Ignores NaN (Not a Number) values.
- Has no axis parameter, so it always calculates the mean of the entire array.

**np.average():**

- Calculates the weighted average of the array elements.
- Allows for specifying weights for each element.
- Has an axis parameter, so you can calculate the average along a specific axis.
- If weights are not provided, it defaults to the arithmetic mean (same as np.mean()).

- **Use np.mean()** when you want the simple arithmetic mean of the entire array, ignoring NaN values.
- **Use np.average()** when You need to calculate the weighted average. You want to specify the axis for calculating the average.


**Q.3** Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.



**Ans:**- Reversing a 1D Array
To reverse a 1D array, you can use slicing. The syntax array[::-1] effectively reverses the order of elements.

Ex.


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

# 1D array

[5 4 3 2 1]


In [ ]:
arr1 = np.array([[1, 2, 3], #2D array
                 [4, 5,6]])
reversed_rows = arr1[::-1] #axis = 0
reversed_columns = arr1[:, ::-1] #axis = 1
print("Original array:\n", arr1)
print("Reversed along rows:\n", reversed_rows )
print("Reversed along columns:\n", reversed_columns)

Original array:
 [[1 2 3]
 [4 5 6]]
Reversed along rows:
 [[4 5 6]
 [1 2 3]]
Reversed along columns:
 [[3 2 1]
 [6 5 4]]


**Q.4** How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.



In [13]:
#Ans:- You can determine the data type of elements in a NumPy array using the dtype attribute:


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int32

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)  # Output: <U6

int64
<U6


Data types are crucial in memory management and performance for several reasons:

1. Memory allocation: NumPy arrays are stored in contiguous blocks of memory. Knowing the data type allows NumPy to allocate the appropriate amount of memory for each element.

2. Memory efficiency: Using the correct data type can reduce memory usage. For example, using int8 instead of int32 for small integers can save memory.

3. Performance: Certain operations are optimized for specific data types. Using the correct data type can lead to faster execution.

4. Type safety: Data types help prevent type-related errors. For example, attempting to store a float in an integer array will raise an error.

5. Interoperability: Data types ensure compatibility with other libraries and languages.



**Q.5** Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?



**Ans:**- In NumPy, ndarrays (n-dimensional arrays) are the core data structure used for storing and manipulating numerical data. They are highly efficient and optimized for performance in scientific computing and data analysis. Here’s a detailed explanation of ndarrays and their key features, along with a comparison to standard Python lists.

Key features:
1. Homogeneous: All elements are of the same data type (e.g., int, float, complex).
2. Multi-dimensional: Can have one or more dimensions (axes).
3. Fixed size: Size is defined at creation and cannot be changed.
4. Contiguous memory: Elements are stored in contiguous memory blocks.
5. Vectorized operations: Supports element-wise operations (e.g., arithmetic, comparison).
6. Broadcasting: Allows operations with differently shaped arrays.

Differences from standard Python lists:

1. Homogeneity: Lists can store elements of different types.
2. Dynamic size: Lists can grow or shrink dynamically.
3. Non-contiguous memory: Elements are stored in separate memory locations.
4. No vectorized operations: Element-wise operations are not supported.
5. No broadcasting: Operations require identical shapes.




**Q.6** Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

**Ans:**- NumPy arrays offer several performance benefits over Python lists for large-scale numerical operations:

1. Speed: NumPy arrays are significantly faster than Python lists for numerical operations due to their vectorized nature and optimized C code.

2. Memory efficiency: NumPy arrays store data in contiguous memory blocks, reducing memory usage and improving cache utilization.

3. Vectorized operations: NumPy arrays support element-wise operations, eliminating the need for loops and reducing overhead.

4. Parallelization: NumPy arrays can be easily parallelized using libraries like Numexpr, Numba, or Cython, taking advantage of multi-core processors.

5. Optimized functions: NumPy provides optimized functions for common numerical operations, such as linear algebra and Fourier transforms.

6. Interoperability: NumPy arrays can be easily converted to and from other formats, like Pandas DataFrames and SciPy sparse matrices.

In contrast, Python lists are:

1. Slower: Python lists are slower due to their dynamic nature and overhead from Python's interpreter.

2. More memory-intensive: Python lists store elements as separate objects, consuming more memory.
3. Less efficient: Python lists require explicit loops for element-wise operations, increasing overhead.


**Q.7** Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.



**Ans:-** NumPy's vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively.

**vstack()**

- Stacks arrays in sequence vertically (row-wise).
- Takes a tuple of arrays as input.
- Output array has shape (M, N), where M is the sum of the number of rows in the input arrays, and N is the number of columns in the input arrays.

**hstack()**

- Stacks arrays in sequence horizontally (column-wise).
- Takes a tuple of arrays as input.
- Output array has shape (M, N), where M is the number of rows in the input arrays, and N is the sum of the number of columns in the input arrays.


In [ ]:
#Example:

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a, b)))  # Output: [[1 2 3] [4 5 6]]

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.hstack((a, b)))  # Output: [[1 2 3 4 5 6]]



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**Q.8** Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.



**Ans:**-NumPy's fliplr() and flipud() methods are used to reverse the order of elements in an array along a specific axis.

**fliplr():**

- Reverses the order of elements along the horizontal axis (axis=1).
- Flips the array from left to right.
- Has no effect on the vertical axis (axis=0).

**flipud():**

- Reverses the order of elements along the vertical axis (axis=0).
- Flips the array from top to bottom.
- Has no effect on the horizontal axis (axis=1).

Effects on various array dimensions:

- 1D array: Both fliplr() and flipud() reverse the order of elements.
- 2D array:
    - fliplr() flips the array horizontally, reversing the order of columns.
    - flipud() flips the array vertically, reversing the order of rows.
- 3D array:
    - fliplr() flips the array horizontally, reversing the order of columns in each plane.
    - flipud() flips the array vertically, reversing the order of rows in each plane.



**Q.9** Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


**Ans:**- he array_split() method in NumPy splits an array into multiple sub-arrays along a specified axis. It takes three arguments:

1. ary: the input array
2. indices_or_sections: the number of splits or the indices at which to split
3. axis: the axis along which to split (default is 0)

Functionality:

- If indices_or_sections is an integer, the array is split into that many equal parts along the specified axis.
- If indices_or_sections is a list of integers, the array is split at those indices along the specified axis.

Handling uneven splits:

- If the length of the array is not divisible by the number of splits, the remaining elements are distributed evenly among the sub-arrays.
- If the number of splits is greater than the length of the array, some sub-arrays will be empty.

Examples:

- np.array_split(ary, 3, axis=0): Split the array into 3 equal parts along the first axis.
- np.array_split(ary, [2, 5], axis=0): Split the array at indices 2 and 5 along the first axis.



**Q.10** Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?


**Ans:**- Vectorization and broadcasting are two fundamental concepts in NumPy that enable efficient array operations.

Vectorization:

- Refers to the ability to perform operations on entire arrays without the need for explicit loops.
- NumPy's vectorized operations work on entire arrays, applying the operation element-wise.
- This leads to significant speedups and reduced memory usage.

Broadcasting:

- Allows arrays with different shapes and sizes to be combined in operations.
- NumPy broadcasts arrays to compatible shapes by replicating elements.
- This enables operations between arrays with different dimensions.

Contribution to efficient array operations:

- Vectorization:
    - Eliminates the need for explicit loops, reducing overhead.
    - Utilizes optimized C code for operations.
- Broadcasting:
    - Enables operations between arrays with different dimensions.
    - Reduces memory usage by avoiding unnecessary copies.


#**Numerical Problems**

**Q.1** Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np
#Create a 3x3 NumPy array with random integers between 1 and 100

array = np.random.randint(1, 101, (3, 3))
print("Original array:")
print(array)

#Interchange rows and columns (transpose the array)
transposed_array = array.T
print("Transposed array:")
print(transposed_array)



Original array:
[[ 7 10 83]
 [ 3 62 85]
 [93 13 61]]
Transposed array:
[[ 7  3 93]
 [10 62 13]
 [83 85 61]]


**Q.2** Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [3]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)
print("1D array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("2x5 array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("5x2 array:")
print(array_5x2)



1D array:
[ 1  2  3  4  5  6  7  8  9 10]
2x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5x2 array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


**Q.3** Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [4]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)
print("4x4 array:")
print(array_4x4)

# Add a border of zeros around it, resulting in a 6x6 array
array_6x6 = np.pad(array_4x4, 1, mode='constant')
print("6x6 array:")
print(array_6x6)



4x4 array:
[[0.33681019 0.68062891 0.58909288 0.72813131]
 [0.03936408 0.56289595 0.50437831 0.90967624]
 [0.63098754 0.29542487 0.59116955 0.48739937]
 [0.39368162 0.96359189 0.3644128  0.86494932]]
6x6 array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.33681019 0.68062891 0.58909288 0.72813131 0.        ]
 [0.         0.03936408 0.56289595 0.50437831 0.90967624 0.        ]
 [0.         0.63098754 0.29542487 0.59116955 0.48739937 0.        ]
 [0.         0.39368162 0.96359189 0.3644128  0.86494932 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**Q.4** Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


**Q.5** Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [7]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array)
lowercase =np.char.lower( array)
title_case = np.char.title(array)
capitalize = np.char.capitalize(array)

print("Original array:")
print(array)
print("Uppercase:")
print(uppercase)
print("Lowercase:")
print(lowercase)
print("Title case:")
print(title_case)
print("Capitalize:")
print(capitalize)



Original array:
['python' 'numpy' 'pandas']
Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
['python' 'numpy' 'pandas']
Title case:
['Python' 'Numpy' 'Pandas']
Capitalize:
['Python' 'Numpy' 'Pandas']


**Q.6** Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [8]:
import numpy as np

# Generate a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words = np.array([(' '.join(word)) for word in words])

print(spaced_words)


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


**Q.7** Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [9]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Perform element-wise addition
addition = array1 + array2
print("Addition:")
print(addition)

# Perform element-wise subtraction
subtraction = array1 - array2
print("Subtraction:")
print(subtraction)

# Perform element-wise multiplication
multiplication = array1 * array2
print("Multiplication:")
print(multiplication)

# Perform element-wise division
division = array1 / array2
print("Division:")
print(division)


Addition:
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
Multiplication:
[[ 5 12]
 [21 32]]
Division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**Q.8** Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [10]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)
print("Identity Matrix:")
print(identity_matrix)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
[1. 1. 1. 1. 1.]


**Q.9** Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [11]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, 100)
print("Random Array:")
print(random_array)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    max_divisor = int(np.sqrt(n)) + 1
    for d in range(3, max_divisor, 2):
        if n % d == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = random_array[np.vectorize(is_prime)(random_array)]
print("Prime Numbers:")
print(prime_numbers)



Random Array:
[652 884 904 934 339  43 909  15 352 119 940  58 313 895 242 392 198 725
  28 569 521 925  33 899 541 400 201 194  94 501 274 170  13 890 775 932
 210 314 702 342 373 814 340 165 338 827 690 238 886 139 568 274 449 442
 138 588 525 812 783 788 513 577 751  52 435  13 240 250  22 600  14 724
 425 505 735 633  88 840 886 430 569 392 473 414 776 856 111  66  16  63
 552 750 607 650 123 332 788 175 827 486]
Prime Numbers:
[ 43 313 569 521 541  13 373 827 139 449 577 751  13 569 607 827]


**Q.10** Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [12]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(50, 90, 30)
print("Daily Temperatures:")
print(daily_temperatures)

# Calculate weekly averages
weekly_temperatures = [np.mean(daily_temperatures[i:i+7]) for i in range(0, 30, 7)]
print("Weekly Averages:")
print(weekly_temperatures)



Daily Temperatures:
[84 89 80 72 69 87 51 71 79 83 66 67 64 52 64 59 88 82 67 65 61 88 79 56
 50 86 60 58 60 76]
Weekly Averages:
[76.0, 68.85714285714286, 69.42857142857143, 68.14285714285714, 68.0]
